name: 'Composer (php-actions)'
description: 'Use the Composer CLI in your Github Actions.'

inputs:
  composer_version:
    description: What version of Composer to use
    default: latest
    required: false

  command:
    description: Composer command to run
    required: true
    default: install

  only_args:
    description: "Only run the desired command with this args. Ignoring all other provided arguments"
    required: false

  interaction:
    description: "Whether to ask any interactive questions. Values: 'yes' or 'no'"
    required: false
    default: no

  dev:
    description: "Whether to install dev packages. Values: 'yes' or 'no'"
    required: false
    default: yes

  progress:
    description: "Whether to output download progress"
    required: false
    default: no

  quiet:
    description: "Whether to suppress all messages"
    required: false
    default: no

  args:
    description: Optional arguments to pass
    required: false

  ssh_key:
    description: The private key contents to use for private repositories
    required: false

  ssh_key_pub:
    description: The public key contents to use for private repositories
    required: false

  ssh_domain:
    description: The domain to gather SSH public keys for (automatic for github.com, gitlab.com, bitbucket.org)
    required: false

  working_dir:
    description: Use the given directory as working directory
    required: false

outputs:
  composer_cache_dir:
    description: "Where composer created its cache"
    value: ${{ steps.composer_run.outputs.composer_cache_dir }}

  composer_major_version:
    description: "Major version of the composer run (can be used as part of the cache key)"
    value: ${{ steps.composer_run.outputs.composer_major_version }}

  composer_version:
    description: "Exact version of the composer run"
    value: ${{ steps.composer_run.outputs.composer_major_version }}

  full_command:
    description: "The full command passed to docker to run"
    value: ${{ steps.composer_run.putputs.full_command }}

runs:
  using: "composite"
  steps:
    - env:
        ACTION_COMPOSER_VERSION: ${{ inputs.composer_version }}
        ACTION_COMMAND: ${{ inputs.command }}
        ACTION_ONLY_ARGS: ${{ inputs.only_args }}
        ACTION_INTERACTION: ${{ inputs.interaction }}
        ACTION_DEV: ${{ inputs.dev }}
        ACTION_PROGRESS: ${{ inputs.progress }}
        ACTION_QUIET: ${{ inputs.quiet }}
        ACTION_ARGS: ${{ inputs.args }}
        ACTION_SSH_KEY: ${{ inputs.ssh_key }}
        ACTION_SSH_KEY_PUB: ${{ inputs.ssh_key_pub }}
        ACTION_SSH_DOMAIN: ${{ inputs.ssh_domain }}
        ACTION_WORKING_DIR: ${{ inputs.working_dir }}
      id: composer_run
      run: ${{ github.action_path }}/composer-action.bash
      shell: bash

branding:
  icon: 'package'  
  color: 'purple'
